export const APP_FLOW_ACTIONS = {
  LOADING_COMPLETED: "LOADING_COMPLETED",
  UPDATE_GOTO: "UPDATE_GOTO",
  SET_COUNTRIES_OPTIONS: "SET_COUNTRIES_OPTIONS",
  SET_COUNTRIES_OPTIONS_COMPLETED: "SET_COUNTRIES_OPTIONS_COMPLETED",
  SET_TIMEZONES_OPTIONS: "SET_TIMEZONES_OPTIONS",
  SET_TIMEZONES_OPTIONS_COMPLETED: "SET_TIMEZONES_OPTIONS_COMPLETED",
};
