name: CI/CD for Next.js

on:
  push:
    branches:
      - develop  # hoặc branch bạn muốn deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Thay đổi nếu bạn sử dụng phiên bản khác

      - name: Install dependencies
        working-directory: ocaplatform  # Thay đổi đường dẫn đến thư mục ocaplatform
        run: npm install

      - name: Build application
        working-directory: ocaplatform  # Thay đổi đường dẫn đến thư mục ocaplatform
        run: npm run build

      - name: Build Docker image
        working-directory: ocaplatform  # Thay đổi đường dẫn đến thư mục ocaplatform
        run: |
          docker build -t my-nextjs-app .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push Docker image
        run: |
          docker tag my-nextjs-app:latest <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/my-nextjs-app:latest
          docker push <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/my-nextjs-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/my-nextjs-app:latest
            docker stop my-nextjs-app || true
            docker rm my-nextjs-app || true
            docker run -d -p 80:3000 --name my-nextjs-app <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/my-nextjs-app:latest
